#!/usr/bin/env python
# -*- coding: utf-8 -*-
#HW3 for EECS 598 Motion Planning
import time
import openravepy

#### YOUR IMPORTS GO HERE ####
import IPython
import numpy as np
import matplotlib.pyplot as plt
#### END OF YOUR IMPORTS ####

if not __openravepy_build_doc__:
    from openravepy import *
    from numpy import *

def waitrobot(robot):
    """busy wait for robot completion"""
    while not robot.GetController().IsDone():
        time.sleep(0.01)

def tuckarms(env,robot):
    with env:
        jointnames = ['l_shoulder_lift_joint','l_elbow_flex_joint','l_wrist_flex_joint','r_shoulder_lift_joint','r_elbow_flex_joint','r_wrist_flex_joint']
        robot.SetActiveDOFs([robot.GetJoint(name).GetDOFIndex() for name in jointnames])
        robot.SetActiveDOFValues([1.29023451,-2.32099996,-0.69800004,1.27843491,-2.32100002,-0.69799996])        
        robot.GetController().SetDesired(robot.GetDOFValues())
    waitrobot(robot)

def plotStatistics(time, nodes, samples, goalbias):
    print "\n\n===== Summary of Simulations ====="
    #print "Average Time    : %f" % (np.average(time))
    #print "Average Samples : %f" % (np.average(samples))
    #print "Average Nodes   : %f" % (np.average(nodes))

    plt.rcParams.update({'font.size': 22})

    f_handle = file('goalBias.txt', 'a')
    np.save(f_handle, goalbias)
    np.save(f_handle, time)
    np.save(f_handle, nodes)
    np.save(f_handle, samples)
    f_handle.close()
    

if __name__ == "__main__":

    env = Environment()
    env.SetViewer('qtcoin')
    collisionChecker = RaveCreateCollisionChecker(env,'ode')
    env.SetCollisionChecker(collisionChecker)

    env.Reset()        
    # load a scene from ProjectRoom environment XML file
    env.Load('hw3.env.xml')
    time.sleep(0.1)

    # 1) get the 1st robot that is inside the loaded scene
    # 2) assign it to the variable named 'robot'
    robot = env.GetRobots()[0]

    ### INITIALIZE YOUR PLUGIN HERE ###
    RaveLoadPlugin('rrtconnect/build/rrtconnect')
    RRTConnect = RaveCreateModule(env,'RRTConnect')
    env.AddModule(RRTConnect,args='')
    ### END INITIALIZING YOUR PLUGIN ###

    # tuck in the PR2's arms for driving
    tuckarms(env,robot)
  
    #set start config
    jointnames =['l_shoulder_pan_joint','l_shoulder_lift_joint','l_elbow_flex_joint','l_upper_arm_roll_joint','l_forearm_roll_joint','l_wrist_flex_joint','l_wrist_roll_joint']
    robot.SetActiveDOFs([robot.GetJoint(name).GetDOFIndex() for name in jointnames])      
    startconfig = [-0.15,0.075,-1.008,0,0,-0.11,0]
    robot.SetActiveDOFValues(startconfig)
    robot.GetController().SetDesired(robot.GetDOFValues())
    waitrobot(robot)

    with env:
        # goalconfig = [0.449,-0.201,-0.151,0,0,-0.11,0]    # Actual goal
        # goalconfig = [0.5255,1.29,-2.12,0,0,-1.38,0]      # level 4 goal
        goalconfig = [0.5255,1.29,-2.12,0,0,-0.11,0]      # level 3 goal
        # goalconfig = [-0.15,1.29,-2.12,0,0,-1.38,0]       # level 2 goal
        # goalconfig = [-0.15,-0.35,-1.73,0,0,-0.11,0]      # level 1 goal

        ### YOUR CODE HERE ###
        NUM_SAMPLES = 10000
        GOAL_BIAS_VAL = 30     # int value between (0, 100]
        STEP_SIZE = 0.2

        # Register the start configuration
        startConfigStr = ' '.join([str(e) for e in startconfig])
        RRTConnect.SendCommand('setstart ' + startConfigStr)

        # Register the goal configuration
        goalConfigStr = ' '.join([str(e) for e in goalconfig])
        RRTConnect.SendCommand('setgoal ' + goalConfigStr)

        # Set the number of samples generated by the RRT before timing out
        RRTConnect.SendCommand('setnumsamples ' + str(NUM_SAMPLES))

        # Set goal biasing percentage (percentabe = 1 / biasVal)
        RRTConnect.SendCommand('setgoalbias ' + str(GOAL_BIAS_VAL))

        # Set step size
        RRTConnect.SendCommand('setstepsize ' + str(STEP_SIZE))

        RRTConnect.SendCommand('init')
        # RRTConnect.SendCommand('printclass')

        time    = np.empty(shape=[0,1])
        samples = np.empty(shape=[0,1])
        nodes   = np.empty(shape=[0,1])
        goalBL  = np.empty(shape=[0,1])

        goalbias = 1;
        while goalbias < 100:
            RRTConnect.SendCommand('resettree')
            RRTConnect.SendCommand('setgoal ' + str(goalbias))
            result = RRTConnect.SendCommand('run')

            data = [int(val) for val in result.split()]
            time = np.append(time, [[data[0]]], axis=0)
            nodes = np.append(nodes, [[data[1]]], axis=0)
            samples = np.append(samples, [[data[2]]], axis=0)
            goalBL = np.append(goalBL, [[goalbias]], axis=0)

            goalbias = goalbias + 5

        plotStatistics(time, nodes, samples, goalbiasList)
 
        ### END OF YOUR CODE ###
    waitrobot(robot)

    raw_input("Press enter to exit...")

